export const site = {
  name: "RidgePoint Remodeling & Carpentry",
  legalName: "RidgePoint Remodeling & Carpentry LLC",
  shortName: "RidgePoint",
  ownerName: "Jason Miller",
  phoneDisplay: "(386) 291-5200",
  phone: "+13862915200",
  email: "jason@ridgepointremodeling.com",
  address: "8831 SW 88th Ct, Lake Butler, FL 32054",
  hours: "Monday through Friday, 8:00 AM to 5:00 PM. Closed major holidays.",
  openingHours: {
    opens: "08:00",
    closes: "17:00",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  },
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://ridgepointremodeling.com",
  serviceAreaSummary: "Based in Lake Butler, Florida, RidgePoint Remodeling & Carpentry serves homeowners within roughly a 60-minute drive, including Starke, Lake City, Gainesville, High Springs, Alachua, Macclenny, Live Oak, Keystone Heights, and nearby rural communities. Availability varies by project scope and schedule.",
  cities: [
    "Lake Butler",
    "Starke",
    "Lake City",
    "Gainesville",
    "High Springs",
    "Alachua",
    "Macclenny",
    "Live Oak",
    "Keystone Heights",
  ],
  locationPages: [
    { city: "Lake Butler", slug: "remodeling-contractor-lake-butler-fl" },
    { city: "Gainesville", slug: "remodeling-contractor-gainesville-fl" },
    { city: "Lake City", slug: "remodeling-contractor-lake-city-fl" },
    { city: "Lake Butler", slug: "deck-builder-lake-butler-fl" },
  ],
};

export const services = [
  {
    slug: "kitchen-remodeling",
    name: "Kitchen Remodeling",
    eyebrow: "The center of daily life",
    summary: "Practical, hard-working kitchens shaped around how your household actually lives.",
    details: ["Layout updates", "Cabinet installation", "Trim and finish carpentry"],
    scopeHeading: "What your kitchen remodel might include",
    scopeDescription: "If your kitchen feels short on storage, difficult to work in, or overdue for a more finished look, a kitchen remodel can focus on the changes that make daily life easier. The right scope starts with how you use the room and what you want to improve first.",
    scopeItems: [
      { title: "Cabinet sales and installation", text: "RidgePoint offers ready-to-assemble cabinets for purchase, with professional installation available for homeowners who want help bringing the kitchen together." },
      { title: "Layout and storage improvements", text: "A more useful layout and better storage can make cooking, cleanup, and everyday routines feel less cramped and more organized." },
      { title: "Trim and finish carpentry", text: "Careful trim and finish work helps cabinets, walls, openings, and the rest of the room meet cleanly and feel complete." },
      { title: "The right scope for your home", text: "The current kitchen, your household routines, and the changes that matter most will help shape a practical path forward." },
    ],
    pageIntro: "A kitchen remodel should solve the everyday problems you notice most: not enough storage, an awkward layout, worn finishes, or a room that no longer fits the way your household lives. RidgePoint helps homeowners plan kitchen improvements around practical use, materials, and the finish details that make the room feel complete.",
    planningPoints: ["What is not working in the current kitchen", "Which changes will make the biggest daily difference", "How cabinetry, trim, and finishes need to work together"],
    serviceFaqs: [
      { question: "Can I improve my kitchen without changing everything?", answer: "Yes. Start by identifying the parts of the kitchen that are creating the most friction. RidgePoint can talk through a focused scope or a more complete remodel based on the room, your priorities, and the result you want." },
      { question: "Can RidgePoint help with kitchen cabinets?", answer: "Yes. Cabinet installation is part of RidgePoint's kitchen work, and ready-to-assemble cabinets are also available for homeowners who want a DIY purchase or cabinet purchase with professional installation." },
      { question: "What should I have ready for a kitchen remodeling estimate?", answer: "You do not need a finished plan. Photos, rough measurements, a list of what is not working, and your preferred timeline give Jason a useful starting point for the conversation." },
    ],
  },
  {
    slug: "bathroom-remodeling",
    name: "Bathroom Remodeling",
    eyebrow: "Comfort that holds up",
    summary: "Thoughtful bathroom renovations, from focused updates to full room transformations.",
    details: ["Vanities and cabinetry", "Tile and finish coordination", "Fixture and lighting updates"],
    scopeHeading: "What your bath remodel might include",
    scopeDescription: "If you are tired of a cramped vanity, dim lighting, worn finishes, or a shower that no longer works for you, a bath remodel might be the change you have been thinking about. The right scope starts with how you want the room to feel and function every day.",
    scopeItems: [
      { title: "Vanity, cabinetry, and storage", text: "A new vanity or better cabinetry can make a tight bathroom easier to use and give everyday items a place to live." },
      { title: "Tile, shower, and tub work", text: "Worn tile, a dated shower, or a tub that no longer fits your routine can be part of a focused update or a more complete bathroom remodel." },
      { title: "Plumbing fixtures and lighting", text: "Updated fixtures and lighting can improve the way the room looks, feels, and functions every day." },
      { title: "The right scope for your home", text: "The condition of the existing bathroom, the changes you want most, and your priorities for the finished space help shape the plan." },
    ],
    pageIntro: "Bathroom work can range from a focused update to a more complete renovation. RidgePoint helps you talk through the condition of the room, the changes you want to make, and the finish decisions that help the space feel comfortable, functional, and easier to maintain.",
    planningPoints: ["The condition of the existing bathroom", "Storage, lighting, and fixture priorities", "The right scope for the room and your goals"],
    serviceFaqs: [
      { question: "Can RidgePoint handle a small bathroom update or does it need to be a full remodel?", answer: "RidgePoint discusses both focused bathroom updates and more complete renovations. Share the current condition of the room and the changes you have in mind so Jason can confirm whether the scope is a fit." },
      { question: "Can I keep my existing bathroom layout and still make a meaningful change?", answer: "Often, yes. Updates to cabinetry, tile, shower or tub areas, fixtures, and lighting can change how the room feels and functions without starting from a blank slate. Jason can talk through what makes sense for your bathroom." },
      { question: "What bathroom work can RidgePoint handle?", answer: "Bathroom remodel scopes can include vanities and cabinetry, tile and finish work, shower or tub updates, plumbing fixtures, and lighting or electrical updates. The right combination depends on the room and your goals." },
      { question: "Do I need every finish selected before I request a free estimate?", answer: "No. A clear description of your goals is enough to start. Photos, the parts of the room that are not working, and any ideas you already have will help guide the conversation. Material and finish choices can be discussed as the scope becomes clearer." },
      { question: "Is RidgePoint licensed and insured?", answer: "Yes. RidgePoint Remodeling & Carpentry LLC is licensed and insured. Florida license number: CRC1335692." },
    ],
  },
  {
    slug: "cabinet-sales-installation",
    name: "Cabinet Sales and Installation",
    eyebrow: "Cabinets your way",
    summary: "Ready-to-assemble cabinets available to purchase for a DIY project or with professional installation.",
    details: ["Ready-to-assemble cabinet sales", "Cabinets for DIY installation", "Professional cabinet installation", "Kitchens, baths, laundry rooms, and built-ins"],
    scopeHeading: "What your cabinet project might include",
    scopeDescription: "Whether you want to install ready-to-assemble cabinets yourself or have RidgePoint handle the installation, the right choice starts with the room, the storage you need, and how involved you want to be in the work.",
    scopeItems: [
      { title: "Quality cabinets built for everyday use", text: "Cabinet collections offer different door styles, finishes, storage options, and construction details so you can choose a look that feels right for the room and works hard every day." },
      { title: "Cabinet purchase with installation", text: "Homeowners can purchase ready-to-assemble cabinets through RidgePoint and include professional installation for one point of contact on the cabinet portion of the project." },
      { title: "Cabinets for the rooms you use", text: "Cabinet options can be discussed for kitchens, bathrooms, laundry rooms, mudrooms, and built-in storage projects." },
      { title: "A fit shaped around your space", text: "Room dimensions, storage goals, door swings, appliances, and the finish details around the cabinetry all help shape the right plan." },
    ],
    pageIntro: "RidgePoint offers a full line of ready-to-assemble cabinets for homeowners who want to handle installation themselves, as well as cabinet purchase and professional installation for homeowners who prefer one point of contact. The right choice depends on your space, your timeline, and how involved you want to be in the work.",
    planningPoints: ["Cabinet options that fit the room and budget", "DIY cabinet purchase versus purchase with installation", "Where careful measuring and finish work matter most"],
    serviceFaqs: [
      { question: "What cabinet brand does RidgePoint offer?", answer: "RidgePoint offers ForeverMark Cabinetry. Jason can help you compare available cabinet collections, door styles, finishes, and construction features around your room, project goals, and budget." },
      { question: "How do I choose cabinets that offer long-term value?", answer: "Start with the storage you need, the way the cabinets will fit the room, the door style and finish you prefer, and the construction features that matter to you. Jason can help you compare ForeverMark Cabinetry options around your project goals and budget." },
      { question: "Can I buy cabinets and install them myself?", answer: "Yes. RidgePoint offers ready-to-assemble cabinets for homeowners who want to purchase cabinets for a DIY installation project." },
      { question: "Can I buy cabinets through RidgePoint and have them installed?", answer: "Yes. Homeowners can purchase ready-to-assemble cabinets through RidgePoint and include professional installation, giving them one point of contact for the cabinet purchase and installation work." },
      { question: "What construction features should I look for in new cabinets?", answer: "Construction details vary by ForeverMark Cabinetry collection. Features available in the cabinet lines RidgePoint offers include 1/2-inch plywood cabinet boxes, 3/4-inch shelves, dovetail wood drawer boxes, full-extension soft-close drawer glides, and concealed soft-close door hinges. Jason can confirm the exact specifications for the cabinet collection you choose." },
      { question: "What should I have ready before I request a cabinet estimate?", answer: "You do not need every detail selected. Photos of the room, rough measurements, the storage problem you want to solve, and any cabinet style ideas you already have are a useful place to start." },
      { question: "What should I compare when I am choosing cabinet options?", answer: "Look at how the cabinets will fit the room, the storage you need, door style and finish, hardware, and whether delivery and installation are part of the plan. Jason can talk through the cabinet and installation option that makes the most sense for your project." },
      { question: "Which rooms can use ready-to-assemble cabinets?", answer: "Cabinet options can be discussed for kitchens, bathrooms, laundry rooms, mudrooms, and built-in storage projects. Tell Jason about the room and the storage problem you want to solve." },
      { question: "Will cabinet installation require a permit?", answer: "Cabinet replacement can be different from a project that moves plumbing, adds electrical, changes walls, or affects appliances. Permit requirements vary by the project and local jurisdiction, so the requirements for your specific scope should be confirmed before work begins." },
    ],
  },
  {
    slug: "custom-carpentry",
    name: "Custom Carpentry",
    eyebrow: "The details make the room",
    summary: "Trim carpentry, custom millwork, and built-ins that give a home its finished character.",
    details: ["Crown molding and baseboards", "Door and window casing", "Custom trim and millwork"],
    scopeHeading: "What your custom carpentry project might include",
    scopeDescription: "When a room feels unfinished, short on storage, or disconnected from the rest of the home, the right trim or built-in can make a practical difference. The best place to start is the detail you want to improve and how you want the room to work.",
    scopeItems: [
      { title: "Built-ins and practical storage", text: "Built-ins can add storage and help a room feel more intentional, especially where an existing wall or unused area is not working as well as it could." },
      { title: "Crown molding, baseboards, and casing", text: "Trim around ceilings, floors, doors, and windows can bring a room together and give new or existing work a more finished look." },
      { title: "Custom trim and millwork", text: "Custom millwork and trim details can shape the character of a room and create a better transition between the features already in the home." },
      { title: "The right fit for your existing home", text: "Existing finishes, room proportions, and the details you want to preserve all help shape a practical scope for the work." },
    ],
    pageIntro: "Finish carpentry is where a room starts to feel intentional. From trim around doors and windows to custom millwork and built-ins, RidgePoint focuses on the clean lines and practical details that help the rest of the work look finished.",
    planningPoints: ["Which details will have the greatest visual impact", "How new trim needs to meet existing finishes", "Storage and built-in opportunities in the room"],
    serviceFaqs: [
      { question: "What does custom carpentry include?", answer: "RidgePoint's custom carpentry work includes trim carpentry, crown molding, baseboards, door and window casing, custom millwork, and built-ins." },
      { question: "Can new trim work with the style and finishes already in my home?", answer: "That is an important part of the planning conversation. Jason can look at how new trim, millwork, or built-ins need to meet existing finishes and help identify the details that will have the strongest impact." },
      { question: "Are built-ins a good fit for my space?", answer: "Built-ins can be useful where storage or a more finished look is needed. Share photos and explain how you want the space to function so RidgePoint can discuss a practical path." },
      { question: "Do I need a complete plan before I ask for an estimate?", answer: "No. Photos of the room, the detail you want to improve, and a simple description of how you want the space to work are enough to begin a useful conversation." },
      { question: "What affects the cost of custom trim or built-ins?", answer: "Cost depends on the size of the space, the amount of trim or millwork involved, materials, existing conditions, and the finish details you choose. An estimate starts by looking at your actual room and priorities." },
      { question: "Can RidgePoint take on a smaller trim project?", answer: "Share the room, the work you have in mind, and your location. RidgePoint can review the details and let you know whether the project is a fit and what the next step looks like." },
    ],
  },
  {
    slug: "deck-building",
    name: "Deck Building",
    eyebrow: "Better time outside",
    summary: "Outdoor decks designed and built for everyday Florida living, entertaining, and connection.",
    details: ["New deck construction", "Deck replacements", "Railings, stairs, and covered features"],
    scopeHeading: "What your deck project might include",
    scopeDescription: "Whether you want a new place to gather outside or an existing deck that feels safe and useful again, the right plan starts with how you want to use the space, connect it to your home, and move through your yard.",
    scopeItems: [
      { title: "New deck construction", text: "A new deck can create a more useful outdoor area for everyday time outside, entertaining, and connecting the home to the yard." },
      { title: "Deck replacement", text: "If an existing deck is worn or no longer working for your home, RidgePoint can discuss a replacement shaped around the space and the way you want to use it." },
      { title: "Railings, stairs, and covered features", text: "The details that shape how a deck feels and functions can include access, stairs, railings, and covered areas." },
      { title: "The right scope for your property", text: "Your yard, the home, the condition of any existing deck, and your priorities for the finished space help shape a practical path forward." },
    ],
    pageIntro: "A deck should give you a more useful place to spend time outside. RidgePoint helps homeowners think through the size, access, railings, stairs, and other practical details that shape how an outdoor space works with the home and yard.",
    planningPoints: ["How you want to use the deck day to day", "Access, stairs, railings, and covered areas", "The condition of an existing deck if replacement is needed"],
    serviceFaqs: [
      { question: "Does RidgePoint build new decks and replace existing decks?", answer: "Yes. RidgePoint discusses new deck construction and deck replacements, along with the practical elements that affect how the space works, including stairs, railings, and covered features." },
      { question: "What should I consider before planning a deck?", answer: "Think about how you want to use the outdoor space, where access should be, and whether stairs, railings, or covered areas are important. Photos of the yard or existing deck are helpful when you reach out." },
      { question: "What should I have ready for a deck estimate?", answer: "You do not need a finished plan. Photos of the yard or current deck, a rough idea of the space you want to improve, your location, and the way you hope to use it are enough to start a useful conversation." },
      { question: "Can I request a quote for a deck in North Florida?", answer: "Yes. RidgePoint serves Lake Butler and North Florida homeowners. Share your location and a brief description of the outdoor space so Jason can confirm the next step." },
    ],
  },
  {
    slug: "flooring-siding-windows",
    name: "Flooring, Siding, and Windows",
    eyebrow: "Practical updates, lasting value",
    summary: "Home improvement updates that refresh worn spaces and help protect the home from the elements.",
    details: ["Flooring replacement", "Siding replacement", "Window replacement", "Project planning and finish carpentry"],
    scopeHeading: "What your flooring, siding, or window project might include",
    scopeDescription: "Worn flooring, aging siding, or windows that no longer feel right can affect how your home looks, feels, and functions. The best next step starts with the condition of the existing materials and the result you want from the update.",
    scopeItems: [
      { title: "Flooring replacement", text: "New flooring can refresh worn spaces and help a room feel more comfortable, practical, and finished." },
      { title: "Siding replacement", text: "Siding updates can renew the exterior appearance of a home and address materials that are worn or no longer serving the home well." },
      { title: "Window replacement", text: "Window replacement can update the look and function of a home while improving the way the finished exterior comes together." },
      { title: "The right scope for your home", text: "The existing materials, the areas you want to improve, and the way the work connects with other finish details all help shape a practical plan." },
    ],
    pageIntro: "Flooring, siding, and window updates can change how a home looks, feels, and functions. RidgePoint helps homeowners discuss the condition of the existing materials, the results they want, and how these improvements fit into the rest of the home.",
    planningPoints: ["The condition and priorities of the existing materials", "Which improvements should be handled together", "How the work connects with interior or exterior finish details"],
    serviceFaqs: [
      { question: "Can RidgePoint help with flooring, siding, and windows?", answer: "Yes. RidgePoint discusses flooring replacement, siding replacement, window replacement, related project planning, and the finish carpentry details that help the completed work come together." },
      { question: "How do I know if my windows may need replacement?", answer: "Difficulty opening or closing a window, visible damage, drafts, or moisture between panes are common reasons homeowners start the conversation. Share photos and what you are noticing so RidgePoint can discuss the condition and a practical next step." },
      { question: "Should windows and siding be updated at the same time?", answer: "That can make sense when the scope of the exterior work overlaps, but it depends on the condition of the home and your priorities. Tell Jason which materials are worn or causing concern so you can discuss what makes sense to handle together." },
      { question: "What should I look for before replacing siding?", answer: "Start with the areas that concern you, such as visible wear, damage, gaps, or places where the exterior no longer looks or feels right. Photos and a description of what you have noticed help begin a useful conversation about the scope." },
      { question: "Can I replace only some windows or one area of siding?", answer: "Every home and project is different. Share the specific windows or exterior area you want to improve so RidgePoint can review the scope and let you know whether the project is a fit." },
      { question: "How should I choose flooring for the room?", answer: "Think about how the room is used every day, the condition of the existing floor, the look you want, and how the new flooring needs to meet nearby rooms or finish details. Those priorities help shape the right conversation." },
      { question: "What information is helpful before I request an estimate?", answer: "Photos of the area, the material or problem you want to address, your location, and your desired outcome are enough to start a useful conversation." },
      { question: "Will permits be needed for my project?", answer: "Permit requirements can vary by the scope of the work and local jurisdiction. RidgePoint can help identify what needs to be confirmed for your specific project before work begins." },
    ],
  },
];

export const getService = (slug) => services.find((service) => service.slug === slug);

export const faqs = [
  {
    question: "Why should I choose RidgePoint Remodeling & Carpentry?",
    answer: "RidgePoint starts with a clear conversation before work begins. Jason listens to what is not working, reviews the details that matter, and helps you understand whether the project is a fit and what the next step may involve. RidgePoint is licensed and insured in Florida, License #CRC1335692.",
  },
  {
    question: "I have had poor communication with a contractor before. What can I expect from RidgePoint?",
    answer: "You should not have to guess what comes next. Before work starts, RidgePoint discusses the existing space, scope, options, materials, timing, and next practical step. The goal is a clearer conversation from the beginning, not a vague promise after the work is already underway.",
  },
  {
    question: "How soon can you start my project?",
    answer: "Start dates depend on the scope, material availability, and the current schedule. Reach out with your project details and location for the most accurate availability.",
  },
  {
    question: "How much will my project cost?",
    answer: "Project cost depends on the condition of the home, materials, and the work involved. RidgePoint discusses the scope with you first, then can provide clear next steps for pricing.",
  },
  {
    question: "How do I know if my project is a fit for RidgePoint?",
    answer: "RidgePoint focuses on kitchen and bath renovations, cabinet sales and installation, finish carpentry, flooring, siding, windows, and porch and deck additions. Share the room, repair, or outdoor space you want to improve so Jason can review the scope with you.",
  },
  {
    question: "Do I need every material and detail selected before I ask for an estimate?",
    answer: "No. You can start with the problem you want to solve, photos of the area, your location, and the result you have in mind. The right materials and details are part of the conversation, not something you need to have figured out alone.",
  },
  {
    question: "What if my project needs work outside RidgePoint's normal scope?",
    answer: "RidgePoint will discuss the scope honestly before work begins. If a project includes work outside the services RidgePoint normally handles, Jason can tell you that early so you have a clearer picture of what the project involves.",
  },
  {
    question: "Are you licensed and insured?",
    answer: "Yes. RidgePoint Remodeling & Carpentry is licensed and insured. Florida License #CRC1335692. Ask Jason for any project-specific documentation you need before work is scheduled.",
  },
];

export const processSteps = [
  { title: "Tell Jason what is not working", text: "Start with the room, repair, or outdoor space you want to improve. Share your goals, location, and the details you already know." },
  { title: "Talk through the details", text: "Jason reviews the project with you, discusses the scope and options, and explains the next practical step." },
  { title: "Get a clear path forward", text: "Once the scope, materials, timing, and next steps are clear, you can decide how you want to proceed." },
];
