import { PageFrame } from "../components/page-frame";
import { site } from "../lib/site-data";

export const metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for Ridge Point Remodeling & Carpentry.",
  alternates: { canonical: "/privacy-policy" },
};

export default function PrivacyPolicyPage() {
  return (
    <PageFrame>
      <main className="shell legal-page">
        <p className="eyebrow">Ridge Point Remodeling & Carpentry</p>
        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: September 25, 2026</p>
        <p>This Privacy Policy explains how {site.legalName}, doing business as {site.name}, collects, uses, and protects information when you use {site.url} or contact us about a project.</p>

        <section>
          <h2>Information we collect</h2>
          <p>We may collect information you choose to provide, including your name, phone number, email address, project type, project details, property location, photos, and other information you send when requesting an estimate or contacting us.</p>
          <p>Our website host and security providers may also receive basic technical information generated by your browser or device, such as IP address, browser type, device information, pages requested, and date and time of access.</p>
        </section>

        <section>
          <h2>How we use information</h2>
          <p>We use information to respond to inquiries, discuss potential work, prepare estimates, provide services, communicate about an active or past project, operate and secure the website, and comply with legal obligations.</p>
          <p>Submitting the quote form opens a message in your email application. The information in that message is sent only if you choose to send it. Please do not send Social Security numbers, payment-card information, medical information, or other sensitive information through the website or email.</p>
        </section>

        <section>
          <h2>How information is shared</h2>
          <p>We do not sell or rent personal information. We may share information with service providers that help us operate the website, host email, maintain security, or provide services requested by you. We may also disclose information when required by law or when reasonably necessary to protect our rights, property, safety, customers, or others.</p>
          <p>We do not currently use advertising pixels or public-facing analytics cookies on this website. We may update this policy before adding tools that materially change our data practices.</p>
        </section>

        <section>
          <h2>Cookies and third-party services</h2>
          <p>Most public visitors can use this website without creating an account. The private gallery editor uses a secure, session-based cookie only for authorized administrators. The site may also include links to third-party services, including Facebook, and an embedded Google map. Those services may collect information under their own policies when you use them. Their practices are not controlled by Ridge Point.</p>
        </section>

        <section>
          <h2>Retention and security</h2>
          <p>We retain information for as long as reasonably necessary for the purposes described in this policy, including communicating with you, providing services, maintaining business records, resolving disputes, and meeting legal obligations.</p>
          <p>We use reasonable administrative, technical, and physical safeguards appropriate to the information we handle. No website, email system, or transmission method is completely secure, so we cannot guarantee absolute security.</p>
        </section>

        <section>
          <h2>Your choices and requests</h2>
          <p>You may ask us to access, correct, or delete personal information we hold about you, subject to legal and business-recordkeeping requirements. To make a request or ask a privacy question, contact us using the information below. We may need to verify your identity before acting on a request.</p>
          <p>Ridge Point does not sell or share personal information for targeted advertising. If our practices change, we will update this policy and provide any notices required by applicable law.</p>
        </section>

        <section>
          <h2>Children&apos;s privacy</h2>
          <p>This website is intended for homeowners and adults seeking home-improvement services. It is not directed to children under 13, and we do not knowingly collect personal information from children under 13.</p>
        </section>

        <section>
          <h2>Changes to this policy</h2>
          <p>We may update this Privacy Policy as our website or business practices change. The updated version will be posted on this page with a revised last-updated date.</p>
        </section>

        <section>
          <h2>Contact us</h2>
          <p><strong>{site.legalName}</strong><br />Doing business as {site.name}<br />{site.address}<br /><a href={`tel:${site.phone}`}>{site.phoneDisplay}</a><br /><a href={`mailto:${site.email}`}>{site.email}</a></p>
        </section>
      </main>
    </PageFrame>
  );
}
